@startuml
package project <<Aggregate>>{


class Project <<Aggregate>>{
String id
String projectNo
String projectName
String taskId
----
void process()
void save()
}

class ProjectResult <<Value Object>>

class ProjectMaterial <<Entity>>

class HandleEvent{
Project project
approve()
returnApproval()
}

Project <-- ProjectResult
Project <-- ProjectMaterial
Project <-- HandleEvent



}
@enduml