@startuml
package project <<Aggregate>>{


class Project <<Aggregate>>{
String id
String projectNo
String projectName
String taskId
----
void process()
}

class ProjectResult <<Value Object>>
class ProjectMaterial <<Entity>>

Project <-- ProjectResult
Project <-- ProjectMaterial



}
@enduml